routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if(Auth::check()){
		return view('welcome');
	}
	else{
		return redirect()->action('LoginController@index');
	}
});

Route::get('login', [ 'as' => 'login', 'uses' => 'LoginController@index']);
Route::post('login', [ 'as' => 'login', 'uses' => 'LoginController@login']);

Route::group(['middleware' => 'auth'], function () {
	Route::get('/test','TestController@index');
	//Logs
	Route::get('error-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
	//Change password
	Route::get('/change-password','ChangepasswordController@index');
	Route::post('/change-password','ChangepasswordController@save');
	//Tower
	Route::resource('towers', 'TowerController');
	//Floors
	Route::resource('floors', 'FloorController');
	//Flats
	Route::resource('flats', 'FlatController');
	//Flat Type
	Route::resource('flat-types', 'FlatTypeController');
	//Owners
	Route::resource('owners', 'OwnerController');
	//Renters
	Route::resource('renters', 'RenterController');
	//Parkings
	Route::resource('parkings', 'ParkingController');
	//Tax
	Route::resource('taxes', 'TaxController');
	//Maintenance Rate
	Route::resource('maintenance-rates', 'MaintenanceRateController');
	//Advance Payment
	Route::resource('maintenance-advances', 'MaintenanceAdvanceController');
	//Maintenance Dues
	Route::resource('maintenance-dues', 'MaintenanceDueController');
	Route::get('/maintenance-dues/account/{id}','MaintenanceDueController@accountHistory');
	Route::get('/maintenance-dues/receive-payment/{id}','MaintenanceDueController@getReceive');
	Route::post('/maintenance-dues/receive-payment/{id}','MaintenanceDueController@postReceive');
	//Opening Balance
	Route::resource('opening-balances', 'OpeningBalanceController');
	//Opening Reading
	Route::resource('opening-readings', 'OpeningReadingController');
	//Fixed Load
	Route::resource('fixed-loads', 'FixedLoadController');
	//Fixed Rate
	Route::resource('fixed-rates', 'FixedRateController');
	//Electricity Bills
	Route::resource('electricity-bills', 'ElectricityBillController');
	Route::get('/electricity-bills/account/{id}','ElectricityBillController@accountHistory');
	Route::get('/electricity-bills/receive-payment/{id}','ElectricityBillController@getReceive');
	Route::post('/electricity-bills/receive-payment/{id}','ElectricityBillController@postReceive');
	Route::get('/electricity-bills/print/{id}','ElectricityBillController@Print');
	//Maintenance Payment
	Route::resource('payments', 'PaymentController');
	//Ajax
	Route::get('/checkbox/floors','FloorController@floorsCheckbox');
	Route::get('/dropdown/floors','FloorController@floorsDropdown');
	Route::get('/dropdown/floors1','FloorController@floorsDropdown1');
	Route::get('/dropdown/flats','FlatController@flatsDropdown');
	Route::get('/dropdown/flats1','FlatController@flatsDropdown1');
	Route::get('/input/owner','OwnerController@ownerInput');
	Route::get('/input/owner2','OwnerController@ownerInput2');
	Route::get('/input/owner3','OwnerController@ownerInput3');
	Route::get('/calculate/advance','MaintenanceAdvanceController@calculate');
	Route::get('/theme/color','ThemeController@index');
	//Logout
	Route::get('/logout', function () {
	    Auth::logout();
	    return redirect('/');
	});
});

app/Floor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Floor extends Model
{
    use SoftDeletes;
    public $fillable = ['tower_id','floor_number'];
}

app/Http/Controllers/FloorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Floor;
use App\Tower;
use DB;

class FloorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$floors = Floor::groupBy('tower_id')->select('tower_id', DB::raw('count(*) as total'))->get();
        // echo "<pre>";
        // print_r($floors);
        // die;
        $floors = Floor::groupBy('tower_id')
			->select('floors.*','towers.name as tower_name', DB::raw('count(*) as total'))
			->leftJoin('towers','towers.id','=','floors.tower_id')
            ->get();
        return view('floors.index',compact('floors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $towers = Tower::all();
        return view('floors.create',compact('towers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'tower_id'=>'required',
            'floor_number'=>'required',
        ]);

        $floor_number = $request->floor_number;
        $tower_id = $request->tower_id;
        $count = count($floor_number);
		for($i=0; $i<$count; $i++){
            Floor::create([
                'tower_id'=>$tower_id,
                'floor_number'=>$floor_number[$i],
            ]);
		}
        
        return redirect()->back()->with('success', 'Record successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $floors = DB::table('floors')
            ->select('floors.*','towers.name as tower_name')
            ->leftJoin('towers','towers.id','=','floors.tower_id')
			->where([
            ['floors.tower_id', $id],
            ['floors.deleted_at', NULL],
			])
			->orderBy('floors.id')
            ->get();
            
        return view('floors.show',compact('floors'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $floors = DB::table('floors')
            ->select('floors.*','towers.name as tower_name')
            ->leftJoin('towers','towers.id','=','floors.tower_id')
			->where([
            ['floors.tower_id', $id],
            ['floors.deleted_at', NULL],
			])
			->orderBy('floors.floor_number')
            ->get();

        return view('floors.edit',compact('floors'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'floor_number'=>'required',
        ]);

        $floor = Floor::where('tower_id',$id)->firstOrFail();
        $floor->where('tower_id',$id)->delete();

        $floor_number = $request->floor_number;
        $count = count($floor_number);
		for($i=0; $i<$count; $i++){
            Floor::create([
                'tower_id'=>$id,
                'floor_number'=>$floor_number[$i],
            ]);
		}
        
        return redirect()->back()->with('success', 'Record successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $floor = Floor::where('tower_id',$id)->firstOrFail();
        $floor->where('tower_id',$id)->delete();

        return redirect()->back()->with('success', 'Record successfully deleted!');
    }

    public function floorsCheckbox(Request $request)
    {
        $tower_id = $request->input('tower_id');
        $floors = DB::table('floors')
            ->select('floors.*','towers.name as tower_name')
            ->leftJoin('towers','towers.id','=','floors.tower_id')
			->where([
            ['floors.tower_id', $tower_id],
            ['floors.deleted_at', NULL],
			])
			->orderBy('floors.id')
            ->get();

        foreach ($floors as $value){ ?>
            <input class="floorChkbox" style="margin:5px; vertical-align:middle" type="checkbox" name="floor_number[]" value="<?php echo $value->id.':'.$value->floor_number; ?>" checked/><?php echo $value->floor_number; ?>
        <?php }
    }

    public function floorsDropdown1(Request $request)
    {
        $tower_id = $request->input('tower_id');
        $floors = DB::table('floors')
            ->select('floors.*','towers.name as tower_name')
            ->leftJoin('towers','towers.id','=','floors.tower_id')
			->where([
            ['floors.tower_id', $tower_id],
            ['floors.deleted_at', NULL],
			])
			->orderBy('floors.id')
            ->get();

        ?> <option value = "">Select</option> <?php
        foreach ($floors as $value){ ?>
            <option value="<?php echo $value->id ?>"><?php echo $value->floor_number ?></option>
        <?php }
    }

    public function floorsDropdown(Request $request)
    {
        $tower_id = $request->input('tower_id');
        $floors = DB::table('owners')
            ->select('owners.*','floors.floor_number as floor_number')
            ->leftJoin('floors','floors.id','=','owners.floor_id')
			->where([
            ['owners.tower_id', $tower_id],
            ['owners.deleted_at', NULL],
			])
            ->orderBy('owners.floor_id')
            ->groupBy('owners.tower_id','owners.floor_id')
            ->get();

        ?> <option value = "">Select</option> <?php
        foreach ($floors as $value){ ?>
            <option value="<?php echo $value->floor_id ?>"><?php echo $value->floor_number ?></option>
        <?php }
    }
}

resources/views/floors/create.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Add Floor</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/floors')}}">Floors</a>
            </li>
            <li class="active">Add</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-9">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">

                    <form>
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label for="tower_id">*Tower</label>
                                <select class="form-control" name="tower_id" id="tower_id" required>
                                    @foreach($towers as $value)
                                    <option value="{{$value->id}}">{{$value->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group col-md-4" style="margin-bottom: 0px">
                                <label for="floor_number">*No. of Floors</label>
                                <input type="number" class="form-control" name="floor_number" id="floor_number" min="1" placeholder="Enter number of floors"
                                    required>
                            </div>
                            <div class="form-group col-md-4" style="margin-top: 23px">
                                <button type="button" class="btn btn-info" id="floorAddBtn">Add</button>
                            </div>
                        </div>
                    </form>

                    <div class="floorFormWrapper">

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#floorAddBtn').click(function (event) {
            $('.floorFormWrapper').html('');
            var tower = $('#tower_id option:selected').val();
            var floor = $('#floor_number').val();
            $('.floorFormWrapper').append('<form action="{{ route("floors.store") }}" method="post" class="form-inline floorFormBody">' +
                '{{ csrf_field() }}' +
                '<input type="hidden" name="tower_id" value="' + tower + '"/>' +
                '</form>');
            for (var i = 0; i < floor; i++) {
                $('.floorFormBody').append('<div class="form-group" style="margin:5px 5px 5px 0px">' +
                    '<input type="text" class="form-control" name="floor_number[]" value="'+i+'" placeholder="Enter floor number" required>' +
                    '</div>');
            }
            $('.floorFormBody').append('<button style="display:block; margin-top:15px" type="submit" class="btn btn-primary">Submit</button>');
        });
    });
</script> @endsection

resources/views/floors/edit.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Tower - {{$floors[0]->tower_name}}</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/floors')}}">Floors</a>
            </li>
            <li class="active">Edit</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-9">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">
                    <form class="form-inline" action="{{ route('floors.update', $floors[0]->tower_id) }}" method="post">
                        {{ method_field('put') }} {{ csrf_field() }}
                        @foreach($floors as $value)
                        <div class="form-group" style="margin:5px 5px 5px 0px">
                            <input type="text" class="form-control" name="floor_number[]" value="{{$value->floor_number}}" placeholder="Enter floor number" required>
                        </div>
                        @endforeach
                        <button style="display: block; margin-top: 15px" type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/floors/index.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Floors</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li class="active">Floors</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-12">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-heading mb-15 clearfix">
                    <a class="btn btn-info btn-addon btn-sm pull-right" href="{{url('/floors/create')}}">
                        <i class="fa fa-plus"></i>Add New</a>
                </div>
                <div class="panel-body">
                    <table class="table table-hover" id="dataTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Tower</th>
                                <th>No. of Floors</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($floors as $key=>$value)
                            <tr>
                                <th scope="row">{{++$key}}</th>
                                <td>{{$value->tower_name}}</td>
                                <td>{{noneIfEmpty($value->total)}}</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{{url('/floors/'.$value->tower_id)}}" class="btn btn-primary">
                                            <i class="fa fa-eye"></i> View </a>
                                        <a href="{{url('/floors/'.$value->tower_id.'/edit')}}" class="btn btn-success">
                                            <i class="fa fa-pencil"></i> Edit </a>
                                        <form class="form-inline" action="{{ url('/floors', ['id' => $value->tower_id]) }}" method="post">
                                            {{ method_field('delete') }} {{ csrf_field() }}
                                            <button class="btn btn-danger" onclick="return confirm('Are you sure you want to Delete?');">
                                                <i class="fa fa-trash"></i> Delete</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/floors/show.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Tower - {{$floors[0]->tower_name}}</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/floors')}}">Floors</a>
            </li>
            <li class="active">View</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-6">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            @foreach($floors as $value)
                            <span class="badge badge-primary">Floor - {{$value->floor_number}}</span>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection