routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if(Auth::check()){
		return view('welcome');
	}
	else{
		return redirect()->action('LoginController@index');
	}
});

Route::get('login', [ 'as' => 'login', 'uses' => 'LoginController@index']);
Route::post('login', [ 'as' => 'login', 'uses' => 'LoginController@login']);

Route::group(['middleware' => 'auth'], function () {
	Route::get('/test','TestController@index');
	//Logs
	Route::get('error-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
	//Change password
	Route::get('/change-password','ChangepasswordController@index');
	Route::post('/change-password','ChangepasswordController@save');
	//Tower
	Route::resource('towers', 'TowerController');
	//Floors
	Route::resource('floors', 'FloorController');
	//Flats
	Route::resource('flats', 'FlatController');
	//Flat Type
	Route::resource('flat-types', 'FlatTypeController');
	//Owners
	Route::resource('owners', 'OwnerController');
	//Renters
	Route::resource('renters', 'RenterController');
	//Parkings
	Route::resource('parkings', 'ParkingController');
	//Tax
	Route::resource('taxes', 'TaxController');
	//Maintenance Rate
	Route::resource('maintenance-rates', 'MaintenanceRateController');
	//Advance Payment
	Route::resource('maintenance-advances', 'MaintenanceAdvanceController');
	//Maintenance Dues
	Route::resource('maintenance-dues', 'MaintenanceDueController');
	Route::get('/maintenance-dues/account/{id}','MaintenanceDueController@accountHistory');
	Route::get('/maintenance-dues/receive-payment/{id}','MaintenanceDueController@getReceive');
	Route::post('/maintenance-dues/receive-payment/{id}','MaintenanceDueController@postReceive');
	//Opening Balance
	Route::resource('opening-balances', 'OpeningBalanceController');
	//Opening Reading
	Route::resource('opening-readings', 'OpeningReadingController');
	//Fixed Load
	Route::resource('fixed-loads', 'FixedLoadController');
	//Fixed Rate
	Route::resource('fixed-rates', 'FixedRateController');
	//Electricity Bills
	Route::resource('electricity-bills', 'ElectricityBillController');
	Route::get('/electricity-bills/account/{id}','ElectricityBillController@accountHistory');
	Route::get('/electricity-bills/receive-payment/{id}','ElectricityBillController@getReceive');
	Route::post('/electricity-bills/receive-payment/{id}','ElectricityBillController@postReceive');
	Route::get('/electricity-bills/print/{id}','ElectricityBillController@Print');
	//Maintenance Payment
	Route::resource('payments', 'PaymentController');
	//Ajax
	Route::get('/checkbox/floors','FloorController@floorsCheckbox');
	Route::get('/dropdown/floors','FloorController@floorsDropdown');
	Route::get('/dropdown/floors1','FloorController@floorsDropdown1');
	Route::get('/dropdown/flats','FlatController@flatsDropdown');
	Route::get('/dropdown/flats1','FlatController@flatsDropdown1');
	Route::get('/input/owner','OwnerController@ownerInput');
	Route::get('/input/owner2','OwnerController@ownerInput2');
	Route::get('/input/owner3','OwnerController@ownerInput3');
	Route::get('/calculate/advance','MaintenanceAdvanceController@calculate');
	Route::get('/theme/color','ThemeController@index');
	//Logout
	Route::get('/logout', function () {
	    Auth::logout();
	    return redirect('/');
	});
});

app/MaintenanceDue.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class MaintenanceDue extends Model
{
    use SoftDeletes;
    public $fillable = ['flat_id','entry_date','debit','credit','balance','comments'];
}

app/Http/Controllers/MaintenanceDueController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\MaintenanceDue;
use App\MaintenanceRate;
use App\FlatType;
use App\Owner;
use App\Tower;
use DB;
use Carbon\Carbon;

class MaintenanceDueController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $flat_id = $request->flat_id;
        $towers = DB::table('owners')
            ->select('owners.*','towers.name as name')
            ->leftJoin('towers','towers.id','=','owners.tower_id')
			->where([
            ['owners.deleted_at', NULL],
			])
            ->orderBy('owners.tower_id')
            ->groupBy('owners.tower_id')
            ->get();
        if(!empty($flat_id)){
            $maintenance_dues = DB::table('maintenance_dues')
            ->select(DB::raw('sum(maintenance_dues.debit) as debit_total,sum(maintenance_dues.credit) as credit_total'),'maintenance_dues.*','towers.name as tower_name','floors.floor_number as floor_name','flats.flat_number as flat_name')
            ->leftJoin('flats','flats.id','=','maintenance_dues.flat_id')
            ->leftJoin('towers','towers.id','=','flats.tower_id')
            ->leftJoin('floors','floors.id','=','flats.floor_id')
            ->where('maintenance_dues.flat_id',$flat_id)
            ->whereNull('maintenance_dues.deleted_at')
            ->groupBy('flat_id')
            ->get();
        }
        else{
            $maintenance_dues = DB::table('maintenance_dues')
            ->select(DB::raw('sum(maintenance_dues.debit) as debit_total,sum(maintenance_dues.credit) as credit_total'),'maintenance_dues.*','towers.name as tower_name','floors.floor_number as floor_name','flats.flat_number as flat_name')
            ->leftJoin('flats','flats.id','=','maintenance_dues.flat_id')
            ->leftJoin('towers','towers.id','=','flats.tower_id')
            ->leftJoin('floors','floors.id','=','flats.floor_id')
            ->whereNull('maintenance_dues.deleted_at')
            ->groupBy('flat_id')
            ->get();
        }
        $count = $maintenance_dues->count();
        $now = Carbon::now();
        $current_month = $now->month;
        return view('maintenance_dues.index',compact('maintenance_dues','count','towers','current_month'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $flat_types = FlatType::all();
        return view('maintenance_dues.create',compact('flat_types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::transaction(function () use($request)
		{
            $now = Carbon::now();
            $today = Carbon::today();
            $current_year = $now->year;
            $current_month = $now->month;

            $owners= Owner::all();

            foreach($owners as $value){
                $maintenance_rate = MaintenanceRate::where([
                    ['flat_type_id',$value->flat_type_id],
                    ['applicable_from', '<=', $today],
                ])->orderBy('applicable_from','desc')->first();
                $amount = $maintenance_rate->amount;
                $applicable_from = $maintenance_rate->applicable_from;

                if(Carbon::parse($applicable_from)->lte(Carbon::today())){
                    $data = MaintenanceDue::create([
                        'flat_id'=>$value->flat_id,
                        'debit'=>$amount,
                        'entry_date'=>$today,
                        'comments'=>'Dues initiated',
                    ]);

                    $res = DB::table('maintenance_dues')
                    ->select(DB::raw("SUM(debit) as debit"),DB::raw("SUM(credit) as credit"))
                    ->where([
                        ['flat_id',$value->flat_id],
                        ['deleted_at',NULL],
                        ])
                    ->first();

                    DB::table('maintenance_dues')
                    ->where('id', $data->id)
                    ->update(['balance' => $res->debit - $res->credit]);

                }
            }
        });

        return redirect()->back()->with('success', 'Record successfully generated!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //$MaintenanceDue = MaintenanceDue::find($id);
        $MaintenanceDue = DB::table('maintenance_dues')
			->select('maintenance_dues.*','flat_types.name as flat_type_name')
			->leftJoin('flat_types','flat_types.id','=','maintenance_dues.flat_type_id')
			->where([
			['maintenance_dues.id', $id],
			])
            ->first();
        return view('maintenance_dues.show',compact('MaintenanceDue'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $MaintenanceDue = MaintenanceDue::find($id);
        $flat_types = FlatType::all();
        return view('maintenance_dues.edit',compact('MaintenanceDue','flat_types'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'flat_type_id'=>'required',
            'type'=>'required',
            'rate'=>'required',
            'applicable_from'=>'required',
        ]);

        if($request->type == '2'){
            $flat_type = FlatType::find($request->flat_type_id);
            $area = $flat_type->area;
            $amount = $request->rate*$area;
        }
        else{
            $amount = $request->rate;
        }

        MaintenanceDue::find($id)->update([
            'flat_type_id'=>$request->flat_type_id,
            'type'=>$request->type,
            'rate'=>$request->rate,
            'amount'=>$amount,
            'applicable_from'=> date_format(date_create($request->applicable_from),"Y-m-d")
        ]);
        
        return redirect()->back()->with('success', 'Record successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $MaintenanceDue = MaintenanceDue::findOrFail($id);

        $MaintenanceDue->delete();

        return redirect()->back()->with('success', 'Record successfully deleted!');
    }

    public function accountHistory($flat_id)
    {
        $flats = DB::table('maintenance_dues')
			->where([
            ['flat_id', $flat_id],  
			['deleted_at', NULL],
			])
			->orderBy('id')
            ->get();

        return view('maintenance_dues.account',compact('flats','flat_id'));
    }

    public function getReceive($flat_id)
    {
        return view('maintenance_dues.receive',compact('flat_id'));
    }

    public function postReceive(Request $request, $flat_id)
    {
        $this->validate($request,[
            'credit'=>'required',
            'entry_date'=>'required|date',
            'comments'=>'required',
        ]);

        DB::transaction(function () use($request, $flat_id)
		{
            $data = MaintenanceDue::create([
                'flat_id'=>$flat_id,
                'entry_date'=>date_ymd($request->entry_date),
                'credit'=>$request->credit,
                'comments'=>$request->comments,
            ]);
    
            $res = DB::table('maintenance_dues')
            ->select(DB::raw("SUM(debit) as debit"),DB::raw("SUM(credit) as credit"))
            ->where([
                ['flat_id',$flat_id],
                ['deleted_at',NULL],
                ])
            ->first();
    
            DB::table('maintenance_dues')
            ->where('id', $data->id)
            ->update(['balance' => $res->debit - $res->credit]);

        });

        return redirect()->back()->with('success', 'Payment successfully received!');
    }
}

resources/views/maintenance_dues/account.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Account History</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/maintenance-dues')}}">Maintenance Dues</a>
            </li>
            <li class="active">Account History</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-12">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-heading mb-15 clearfix">
                    <a class="btn btn-info btn-addon btn-sm pull-right" href="{{url('/maintenance-dues/receive-payment/'.$flat_id)}}">
                        <i class="fa fa-money"></i>Receive Payment</a>
                </div>
                <div class="panel-body">
                    <table class="table table-hover" id="dataTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Particular</th>
                                <th>Debit</th>
                                <th>Credit</th>
                                <th>Balance</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($flats as $key=>$value)
                            <tr>
                                <th scope="row">{{++$key}}</th>
                                <td>{{$value->comments}}</td>
                                <td>{{$value->debit}}</td>
                                <td>{{$value->credit}}</td>
                                <td>{{$value->balance}}</td>
                                <td>{{date_dfy($value->entry_date)}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/maintenance_dues/create.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Add Maintenance Dues</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/maintenance-rates')}}">Maintenance Dues</a>
            </li>
            <li class="active">Add</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-6">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">
                    <form action="{{ route('maintenance-rates.store') }}" method="post">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="flat_type_id">*Flat Type</label>
                            <select class="form-control" name="flat_type_id" required>
                                @foreach($flat_types as $value)
                                <option value="{{$value->id}}">{{$value->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="type">*Type</label>
                            <br/>
                            <label>
                                <input type="radio" name="type" value="1">Fixed</label>
                            <label>
                                <input type="radio" name="type" value="2">Per Square Feet</label>
                        </div>
                        <div class="form-group">
                            <label for="rate">*Rate</label>
                            <input type="number" class="form-control" name="rate" min="0" placeholder="Enter rate" required>
                        </div>
                        <div class="form-group">
                            <label for="applicable_from">*Applicable From</label>
                            <input type="text" class="form-control" id="datePicker" name="applicable_from" min="0" placeholder="Enter applicable from"
                                required>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/maintenance_dues/edit.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Edit Maintenance Due</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/maintenance-rates')}}">Maintenance Dues</a>
            </li>
            <li class="active">Edit</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-6">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">
                    <form action="{{ route('maintenance-rates.update', $MaintenanceDue->id) }}" method="post">
                        {{ method_field('put') }}
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="flat_type_id">*Flat Type</label>
                            <select class="form-control" name="flat_type_id" required>
                                @foreach($flat_types as $value)
                                <option value="{{$value->id}}" @if($MaintenanceDue->flat_type_id == $value->id) selected @endif>{{$value->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="type">*Type</label>
                            <br/>
                            <label>
                                <input type="radio" name="type" value="1" @if($MaintenanceDue->type == '1') checked @endif>Fixed</label>
                            <label>
                                <input type="radio" name="type" value="2" @if($MaintenanceDue->type == '2') checked @endif>Per Square Feet</label>
                        </div>
                        <div class="form-group">
                            <label for="rate">*Rate</label>
                            <input type="number" class="form-control" name="rate" value="{{$MaintenanceDue->rate}}" min="0" placeholder="Enter rate" required>
                        </div>
                        <div class="form-group">
                            <label for="applicable_from">*Applicable From</label>
                            <input type="text" class="form-control" id="datePicker" name="applicable_from" value="{{date_format(date_create($MaintenanceDue->applicable_from),'d-M-Y')}}" min="0" placeholder="Enter applicable from" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/maintenance_dues/index.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Maintenance Dues</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li class="active">Maintenance Dues</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-12">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                @if(!duesGenerated($current_month))
                <form action="{{ route('maintenance-dues.store') }}" method="post">
                {{ csrf_field() }}
                <div class="panel-heading clearfix">
                    <button type="submit" class="btn btn-info btn-addon btn-sm pull-right"><i class="fa fa-plus"></i>Generate This Month Maintenace Dues</button>
                </div>
                </form>
                @endif
                <div class="panel-body">
                    <div class="row">
                        <form>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label for="name">Tower</label>
                                    <select class="form-control" id="towerOptions" onChange="getFloors(this.value);" required>
                                        <option value="">Select</option>
                                        @foreach($towers as $value)
                                        <option value="{{$value->tower_id}}">{{$value->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group" style="margin-bottom: 0px">
                                    <label for="floor">Floor</label>
                                    <select class="form-control" id="floorOptions" onChange="getFlats(document.getElementById('towerOptions').value,this.value);" required>
                                        <option value="">Select</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group" style="margin-bottom: 0px">
                                    <label for="floor">Flat</label>
                                    <select class="form-control" name="flat_id" id="flatOptions" required>
                                        <option value="">Select</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <button style="margin-top:23px" type="submit" class="btn btn-primary">Find</button>
                            </div>
                        </form>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Tower</th>
                                            <th>Floor</th>
                                            <th>Flat</th>
                                            <th>Total</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if($count>0)
                                        @foreach($maintenance_dues as $key=>$value)
                                            <tr>
                                                <td>{{++$key}}</td>
                                                <td>{{$value->tower_name}}</td>
                                                <td>{{$value->floor_name}}</td>
                                                <td>{{$value->flat_name}}</td>
                                                <td>{{$value->debit_total-$value->credit_total}}</td>
                                                <td>
                                                    <div class="btn-group">
                                                        <a href="{{url('/maintenance-dues/account/'.$value->flat_id)}}" class="btn btn-success">
                                                            <i class="fa fa-history"></i> Account History </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                        @else
                                            <tr>
                                                <td class="text-center" colspan="6">No Records Found</td>
                                            </tr>
                                        @endif
                                    </tbody>
                                </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function getFloors(val) {
        $.ajax({
            type: "GET",
            url: "{{url('/dropdown/floors')}}",
            data: 'tower_id=' + val,
            success: function (data) {
                $("#floorOptions").html('');
                $("#flatOptions").html('<option value="">Select</option>');
                $("#floorOptions").html(data);
            }
        });
    }
    function getFlats(val1, val2) {
        $.ajax({
            type: "GET",
            url: "{{url('/dropdown/flats')}}",
            data: 'tower_id=' + val1 + '&floor_id=' + val2,
            success: function (data) {
                $("#flatOptions").html('');
                $("#flatOptions").html(data);
            }
        });
    }
</script> @endsection

resources/views/maintenance_dues/receive.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Receive Payment</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/maintenance-dues')}}">Maintenance Dues</a>
            </li>
            <li>
                <a href="{{url('/maintenance-dues/account/'.$flat_id)}}">Account History</a>
            </li>
            <li class="active">Receive Payment</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-6">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">
                    <form method="post">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="credit">*Amount</label>
                            <input type="number" class="form-control" name="credit" min="0" step="0.01" placeholder="Enter amount" required>
                        </div>
                        <div class="form-group">
                            <label for="entry_date">*Date</label>
                            <input type="text" class="form-control" name="entry_date" id="datePicker" placeholder="Enter date" required>
                        </div>
                        <div class="form-group">
                            <label for="comments">*Remarks</label>
                            <textarea class="form-control" name="comments" placeholder="Enter remarks" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/maintenance_dues/show.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>View Maintenance Due</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/maintenance-rates')}}">Maintenance Dues</a>
            </li>
            <li class="active">View</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-9">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-3">
                            <label class="text-success">Flat Type</label>
                            <p>{{$MaintenanceDue->flat_type_name}}</p>
                        </div>
                        <div class="col-md-3">
                            <label class="text-success">Type</label>
                            <p>
                                @if($MaintenanceDue->type == '1') Fixed @endif @if($MaintenanceDue->type == '2') Per Square Feet @endif
                            </p>
                        </div>
                        <div class="col-md-3">
                            <label class="text-success">Rate</label>
                            <p>{{noneIfEmpty($MaintenanceDue->rate)}}</p>
                        </div>
                        <div class="col-md-3">
                            <label class="text-success">Applicable From</label>
                            <p>{{date_dfy($MaintenanceDue->applicable_from)}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection