routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if(Auth::check()){
		return view('welcome');
	}
	else{
		return redirect()->action('LoginController@index');
	}
});

Route::get('login', [ 'as' => 'login', 'uses' => 'LoginController@index']);
Route::post('login', [ 'as' => 'login', 'uses' => 'LoginController@login']);

Route::group(['middleware' => 'auth'], function () {
	Route::get('/test','TestController@index');
	//Logs
	Route::get('error-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
	//Change password
	Route::get('/change-password','ChangepasswordController@index');
	Route::post('/change-password','ChangepasswordController@save');
	//Tower
	Route::resource('towers', 'TowerController');
	//Floors
	Route::resource('floors', 'FloorController');
	//Flats
	Route::resource('flats', 'FlatController');
	//Flat Type
	Route::resource('flat-types', 'FlatTypeController');
	//Owners
	Route::resource('owners', 'OwnerController');
	//Renters
	Route::resource('renters', 'RenterController');
	//Parkings
	Route::resource('parkings', 'ParkingController');
	//Tax
	Route::resource('taxes', 'TaxController');
	//Maintenance Rate
	Route::resource('maintenance-rates', 'MaintenanceRateController');
	//Advance Payment
	Route::resource('maintenance-advances', 'MaintenanceAdvanceController');
	//Maintenance Dues
	Route::resource('maintenance-dues', 'MaintenanceDueController');
	Route::get('/maintenance-dues/account/{id}','MaintenanceDueController@accountHistory');
	Route::get('/maintenance-dues/receive-payment/{id}','MaintenanceDueController@getReceive');
	Route::post('/maintenance-dues/receive-payment/{id}','MaintenanceDueController@postReceive');
	//Opening Balance
	Route::resource('opening-balances', 'OpeningBalanceController');
	//Opening Reading
	Route::resource('opening-readings', 'OpeningReadingController');
	//Fixed Load
	Route::resource('fixed-loads', 'FixedLoadController');
	//Fixed Rate
	Route::resource('fixed-rates', 'FixedRateController');
	//Electricity Bills
	Route::resource('electricity-bills', 'ElectricityBillController');
	Route::get('/electricity-bills/account/{id}','ElectricityBillController@accountHistory');
	Route::get('/electricity-bills/receive-payment/{id}','ElectricityBillController@getReceive');
	Route::post('/electricity-bills/receive-payment/{id}','ElectricityBillController@postReceive');
	Route::get('/electricity-bills/print/{id}','ElectricityBillController@Print');
	//Maintenance Payment
	Route::resource('payments', 'PaymentController');
	//Ajax
	Route::get('/checkbox/floors','FloorController@floorsCheckbox');
	Route::get('/dropdown/floors','FloorController@floorsDropdown');
	Route::get('/dropdown/floors1','FloorController@floorsDropdown1');
	Route::get('/dropdown/flats','FlatController@flatsDropdown');
	Route::get('/dropdown/flats1','FlatController@flatsDropdown1');
	Route::get('/input/owner','OwnerController@ownerInput');
	Route::get('/input/owner2','OwnerController@ownerInput2');
	Route::get('/input/owner3','OwnerController@ownerInput3');
	Route::get('/calculate/advance','MaintenanceAdvanceController@calculate');
	Route::get('/theme/color','ThemeController@index');
	//Logout
	Route::get('/logout', function () {
	    Auth::logout();
	    return redirect('/');
	});
});

app/Http/Controllers/FlatTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\FlatType;

class FlatTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $flat_types = FlatType::all();
        return view('flat_types.index',compact('flat_types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('flat_types.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required|max:255',
            'rooms'=>'required',
            'wash_rooms'=>'required',
            'store_rooms'=>'required',
            'area'=>'required',
        ]);

        FlatType::create($request->all());
        
        return redirect()->back()->with('success', 'Record successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $FlatType = FlatType::find($id);
        return view('flat_types.show',compact('FlatType'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $FlatType = FlatType::find($id);
        return view('flat_types.edit',compact('FlatType'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'=>'required|max:255',
            'rooms'=>'required',
            'wash_rooms'=>'required',
            'store_rooms'=>'required',
            'area'=>'required',
        ]);

        FlatType::find($id)->update($request->all());
        
        return redirect()->back()->with('success', 'Record successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $FlatType = FlatType::findOrFail($id);

        $FlatType->delete();

        return redirect()->back()->with('success', 'Record successfully deleted!');
    }
}

resources/views/flat_types/create.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Add Flat Types</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/flat-types')}}">Flat Types</a>
            </li>
            <li class="active">Add</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-6">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">
                    <form action="{{ route('flat-types.store') }}" method="post">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="name">*Name</label>
                            <input type="text" class="form-control" name="name" placeholder="Enter name" required>
                        </div>
                        <div class="form-group">
                            <label for="rooms">*Rooms</label>
                            <input type="number" class="form-control" name="rooms" min="0" placeholder="Enter number of rooms" required>
                        </div>
                        <div class="form-group">
                            <label for="wash_rooms">*Washrooms</label>
                            <input type="number" class="form-control" name="wash_rooms" min="0" placeholder="Enter number of wash rooms" required>
                        </div>
                        <div class="form-group">
                            <label for="store_rooms">*Store/Servant Rooms</label>
                            <input type="number" class="form-control" name="store_rooms" min="0" placeholder="Enter number of store rooms" required>
                        </div>
                        <div class="form-group">
                            <label for="area">*Area/Size</label>
                            <input type="text" class="form-control" name="area" placeholder="Enter area" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/flat_types/edit.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Edit Flat Type</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/flat-types')}}">Flat Types</a>
            </li>
            <li class="active">Edit</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-6">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">
                    <form action="{{ route('flat-types.update', $FlatType->id) }}" method="post">
                        {{ method_field('put') }}
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="name">*Name</label>
                            <input type="text" class="form-control" name="name" value="{{$FlatType->name}}" placeholder="Enter name" required>
                        </div>
                        <div class="form-group">
                            <label for="rooms">*Rooms</label>
                            <input type="number" class="form-control" name="rooms" value="{{$FlatType->rooms}}" min="0" placeholder="Enter number of rooms" required>
                        </div>
                        <div class="form-group">
                            <label for="wash_rooms">*Washrooms</label>
                            <input type="number" class="form-control" name="wash_rooms" value="{{$FlatType->wash_rooms}}" min="0" placeholder="Enter number of wash rooms" required>
                        </div>
                        <div class="form-group">
                            <label for="store_rooms">*Store/Servant Rooms</label>
                            <input type="number" class="form-control" name="store_rooms" value="{{$FlatType->store_rooms}}" min="0" placeholder="Enter number of store rooms" required>
                        </div>
                        <div class="form-group">
                            <label for="area">*Area/Size</label>
                            <input type="text" class="form-control" name="area" value="{{$FlatType->area}}" placeholder="Enter area" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/flat_types/index.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Flat Types</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li class="active">Flat Types</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-12">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-heading mb-15 clearfix">
                    <a class="btn btn-info btn-addon btn-sm pull-right" href="{{url('/flat-types/create')}}">
                        <i class="fa fa-plus"></i>Add New</a>
                </div>
                <div class="panel-body">
                    <table class="table table-hover" id="dataTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Rooms</th>
                                <th>Wash Rooms</th>
                                <th>Store/Servant Rooms</th>
                                <th>Area/Size</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($flat_types as $key=>$value)
                            <tr>
                                <th scope="row">{{++$key}}</th>
                                <td>{{$value->name}}</td>
                                <td>{{$value->rooms}}</td>
                                <td>{{$value->wash_rooms}}</td>
                                <td>{{$value->store_rooms}}</td>
                                <td>{{$value->area}}</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{{url('/flat-types/'.$value->id)}}" class="btn btn-primary">
                                            <i class="fa fa-eye"></i> View </a>
                                        <a href="{{url('/flat-types/'.$value->id.'/edit')}}" class="btn btn-success">
                                            <i class="fa fa-pencil"></i> Edit </a>
                                        <form class="form-inline" action="{{ url('/flat-types', ['id' => $value->id]) }}" method="post">
                                            {{ method_field('delete') }} {{ csrf_field() }}
                                            <button class="btn btn-danger" onclick="return confirm('Are you sure you want to Delete?');">
                                                <i class="fa fa-trash"></i> Delete</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/flat_types/show.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>View Flat Type</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/flat-types')}}">Flat Types</a>
            </li>
            <li class="active">View</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-9">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="text-success">Name</label>
                            <p>{{$FlatType->name}}</p>
                        </div>
                        <div class="col-md-4">
                            <label class="text-success">Rooms</label>
                            <p>{{noneIfEmpty($FlatType->rooms)}}</p>
                        </div>
                        <div class="col-md-4">
                            <label class="text-success">Wash Rooms</label>
                            <p>{{noneIfEmpty($FlatType->wash_rooms)}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label class="text-success">Store Rooms</label>
                            <p>{{$FlatType->store_rooms}}</p>
                        </div>
                        <div class="col-md-4">
                            <label class="text-success">Area</label>
                            <p>{{noneIfEmpty($FlatType->area)}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection