routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if(Auth::check()){
		return view('welcome');
	}
	else{
		return redirect()->action('LoginController@index');
	}
});

Route::get('login', [ 'as' => 'login', 'uses' => 'LoginController@index']);
Route::post('login', [ 'as' => 'login', 'uses' => 'LoginController@login']);

Route::group(['middleware' => 'auth'], function () {
	Route::get('/test','TestController@index');
	//Logs
	Route::get('error-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
	//Change password
	Route::get('/change-password','ChangepasswordController@index');
	Route::post('/change-password','ChangepasswordController@save');
	//Tower
	Route::resource('towers', 'TowerController');
	//Floors
	Route::resource('floors', 'FloorController');
	//Flats
	Route::resource('flats', 'FlatController');
	//Flat Type
	Route::resource('flat-types', 'FlatTypeController');
	//Owners
	Route::resource('owners', 'OwnerController');
	//Renters
	Route::resource('renters', 'RenterController');
	//Parkings
	Route::resource('parkings', 'ParkingController');
	//Tax
	Route::resource('taxes', 'TaxController');
	//Maintenance Rate
	Route::resource('maintenance-rates', 'MaintenanceRateController');
	//Advance Payment
	Route::resource('maintenance-advances', 'MaintenanceAdvanceController');
	//Maintenance Dues
	Route::resource('maintenance-dues', 'MaintenanceDueController');
	Route::get('/maintenance-dues/account/{id}','MaintenanceDueController@accountHistory');
	Route::get('/maintenance-dues/receive-payment/{id}','MaintenanceDueController@getReceive');
	Route::post('/maintenance-dues/receive-payment/{id}','MaintenanceDueController@postReceive');
	//Opening Balance
	Route::resource('opening-balances', 'OpeningBalanceController');
	//Opening Reading
	Route::resource('opening-readings', 'OpeningReadingController');
	//Fixed Load
	Route::resource('fixed-loads', 'FixedLoadController');
	//Fixed Rate
	Route::resource('fixed-rates', 'FixedRateController');
	//Electricity Bills
	Route::resource('electricity-bills', 'ElectricityBillController');
	Route::get('/electricity-bills/account/{id}','ElectricityBillController@accountHistory');
	Route::get('/electricity-bills/receive-payment/{id}','ElectricityBillController@getReceive');
	Route::post('/electricity-bills/receive-payment/{id}','ElectricityBillController@postReceive');
	Route::get('/electricity-bills/print/{id}','ElectricityBillController@Print');
	//Maintenance Payment
	Route::resource('payments', 'PaymentController');
	//Ajax
	Route::get('/checkbox/floors','FloorController@floorsCheckbox');
	Route::get('/dropdown/floors','FloorController@floorsDropdown');
	Route::get('/dropdown/floors1','FloorController@floorsDropdown1');
	Route::get('/dropdown/flats','FlatController@flatsDropdown');
	Route::get('/dropdown/flats1','FlatController@flatsDropdown1');
	Route::get('/input/owner','OwnerController@ownerInput');
	Route::get('/input/owner2','OwnerController@ownerInput2');
	Route::get('/input/owner3','OwnerController@ownerInput3');
	Route::get('/calculate/advance','MaintenanceAdvanceController@calculate');
	Route::get('/theme/color','ThemeController@index');
	//Logout
	Route::get('/logout', function () {
	    Auth::logout();
	    return redirect('/');
	});
});

app/Flat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Flat extends Model
{
    use SoftDeletes;
    public $fillable = ['tower_id','floor_id','flat_number'];
}

app/FlatType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class FlatType extends Model
{
    use SoftDeletes;
    public $fillable = ['name','rooms','wash_rooms','store_rooms','area'];
}

app/Http/Controllers/FlatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Flat;
use App\Tower;
use App\MaintenanceDue;
use DB;

class FlatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $flats = Flat::groupBy('tower_id','floor_id')
			->select('flats.*','towers.name as tower_name','floors.floor_number as floor_name', DB::raw('count(*) as total'))
            ->leftJoin('towers','towers.id','=','flats.tower_id')
            ->leftJoin('floors','floors.id','=','flats.floor_id')
            ->get();
        return view('flats.index',compact('flats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $towers = Tower::all();
        return view('flats.create',compact('towers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'tower_id'=>'required',
            'floor_number'=>'required',
            'number_flats'=>'required',
        ]);

        $tower_id = $request->tower_id;
        $floor_number = $request->floor_number;
        $number_flats = $request->number_flats;

        $count = count($floor_number);

		for($i=0; $i<$count; $i++){
            for($j=0; $j<$number_flats; $j++){
                
                $floor = explode(":",$floor_number[$i]);
                $floor_no = $floor[1];
                Flat::create([
                    'tower_id'=>$tower_id,
                    'floor_id'=>$floor_number[$i],
                    'flat_number'=>$floor_no.str_pad($j+1,2,'0',STR_PAD_LEFT),
                ]);
            }
        }
        
        return redirect()->back()->with('success', 'Record successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
        $flat = Flat::findOrFail($id);
        $tower_id = $flat->tower_id;
        $floor_id = $flat->floor_id;

        $flats = $flat->select('flats.*','towers.name as tower_name','floors.floor_number as floor_name')
            ->leftJoin('towers','towers.id','=','flats.tower_id')
            ->leftJoin('floors','floors.id','=','flats.floor_id')
            ->orderBy('flats.flat_number')
            ->where([
                ['flats.tower_id',$tower_id],
                ['flats.floor_id',$floor_id],
            ])->get();

        return view('flats.show',compact('flats'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $flat = Flat::findOrFail($id);
        $tower_id = $flat->tower_id;
        $floor_id = $flat->floor_id;

        $flats = $flat->select('flats.*','towers.name as tower_name','floors.floor_number as floor_name')
            ->leftJoin('towers','towers.id','=','flats.tower_id')
            ->leftJoin('floors','floors.id','=','flats.floor_id')
            ->orderBy('flats.flat_number')
            ->where([
                ['flats.tower_id',$tower_id],
                ['flats.floor_id',$floor_id],
            ])->get();
        
        return view('flats.edit',compact('flats'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'flat_number'=>'required',
        ]);

        $flat = Flat::findOrFail($id);
        $tower_id = $flat->tower_id;
        $floor_id = $flat->floor_id;

        $flat->where([
            ['tower_id',$tower_id],
            ['floor_id',$floor_id],
        ])
        ->delete();

        $flat_number = $request->flat_number;
        $count = count($flat_number);

		for($i=0; $i<$count; $i++){
            Flat::create([
                'tower_id'=>$tower_id,
                'floor_id'=>$floor_id,
                'flat_number'=>$flat_number[$i],
            ]);
		}
        
        return redirect()->route('flats.index')->with('success', 'Record successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $flat = Flat::findOrFail($id);
        $tower_id = $flat->tower_id;
        $floor_id = $flat->floor_id;

        $flat->where([
            ['tower_id',$tower_id],
            ['floor_id',$floor_id],
        ])->delete();

        return redirect()->back()->with('success', 'Record successfully deleted!');
    }

    public function flatsDropdown1(Request $request)
    {
        $tower_id = $request->input('tower_id');
        $floor_id = $request->input('floor_id');
        $flats = Flat::where([
            ['tower_id', $tower_id],
            ['floor_id', $floor_id],
            ])
            ->orderBy('flat_number')
            ->get();

        ?> <option value = "">Select</option> <?php
        foreach ($flats as $value){ ?>
            <option value="<?php echo $value->id ?>"><?php echo $value->flat_number ?></option>
        <?php }
    }

    public function flatsDropdown(Request $request)
    {
        $tower_id = $request->input('tower_id');
        $floor_id = $request->input('floor_id');
        $flats = DB::table('owners')
            ->select('owners.*','flats.flat_number as flat_number')
            ->leftJoin('flats','flats.id','=','owners.flat_id')
			->where([
            ['owners.tower_id', $tower_id],
            ['owners.floor_id', $floor_id],
            ['owners.deleted_at', NULL],
			])
            ->orderBy('owners.floor_id')
            ->groupBy('owners.tower_id','owners.floor_id','owners.flat_id')
            ->get();

        ?> <option value = "">Select</option> <?php
        foreach ($flats as $value){ ?>
            <option value="<?php echo $value->flat_id ?>"><?php echo $value->flat_number ?></option>
        <?php }
    }
}

resources/views/flats/create.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Add Flat</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/flats')}}">Flats</a>
            </li>
            <li class="active">Add</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-6">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">

                    <form action="{{ route('flats.store') }}" method="post">
                    {{ csrf_field() }}
                        <div class="form-group">
                            <label for="tower_id">*Tower</label>
                            <select class="form-control" name="tower_id" id="tower_id" onChange="getFloors(this.value);" required>
                            <option value="">Select</option>    
                            @foreach($towers as $value)
                                <option value="{{$value->id}}">{{$value->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group" id="chkWrapper" style="display:none">
                            <label for="floor"><b>Floor Number</b></label>
                            <input type="checkbox" id="selectAll" checked/> Select All
                        </div>
                        <div class="form-group" id="chkBody">
                            
                        </div>
                        <div class="form-group">
                            <label for="number_flats">*Number of Flats</label>
                            <input class="form-control" type="number" name="number_flats" min="0"/>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>

                    <div class="flatFormWrapper">

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#flatAddBtn').click(function (event) {
            $('.flatFormWrapper').html('');
            var tower = $('#tower_id option:selected').val();
            var flat = $('#flat_number').val();
            $('.flatFormWrapper').append('<form action="{{ route("flats.store") }}" method="post" class="form-inline flatFormBody">' +
                '{{ csrf_field() }}' +
                '<input type="hidden" name="tower_id" value="' + tower + '"/>' +
                '</form>');
            for (var i = 0; i < flat; i++) {
                $('.flatFormBody').append('<div class="form-group" style="margin:5px 5px 5px 0px">' +
                    '<input type="text" class="form-control" name="flat_number[]" value="'+i+'" placeholder="Enter flat number" required>' +
                    '</div>');
            }
            $('.flatFormBody').append('<button style="display:block; margin-top:15px" type="submit" class="btn btn-primary">Submit</button>');
        });
    });

    function getFloors(val) {
        $.ajax({
        type: "GET",
        url: "{{url('/checkbox/floors')}}",
        data:'tower_id='+val,
        success: function(data){
            $("#chkBody").html('');
            $("#chkBody").html(data);
            $("#chkWrapper").show();
        }
        });
    }

    $('#selectAll').click(function() {
		if ($(this).is(':checked')) {
			$(".floorChkbox").prop("checked", true);
		}
		else {
			$(".floorChkbox").prop("checked", false);
		}
	});

</script> @endsection

resources/views/flats/edit.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
<h3>{{$flats[0]->tower_name}} &amp; Floor - {{$flats[0]->floor_name}}</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/flats')}}">Flats</a>
            </li>
            <li class="active">Edit</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-9">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">
                    <form class="form-inline" action="{{ route('flats.update', $flats[0]->id) }}" method="post">
                        {{ method_field('put') }} {{ csrf_field() }}
                        @foreach($flats as $value)
                        <div class="form-group" style="margin:5px 5px 5px 0px">
                            <input type="text" class="form-control" name="flat_number[]" value="{{$value->flat_number}}" placeholder="Enter flat number" required>
                        </div>
                        @endforeach
                        <button style="display: block; margin-top: 15px" type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/flats/index.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>Flats</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li class="active">Flats</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-12">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-heading mb-15 clearfix">
                    <a class="btn btn-info btn-addon btn-sm pull-right" href="{{url('/flats/create')}}">
                        <i class="fa fa-plus"></i>Add New</a>
                </div>
                <div class="panel-body">
                    <table class="table table-hover" id="dataTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Tower</th>
                                <th>Floor</th>
                                <th>No. of Flats</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($flats as $key=>$value)
                            <tr>
                                <th scope="row">{{++$key}}</th>
                                <td>{{$value->tower_name}}</td>
                                <td>{{$value->floor_name}}</td>
                                <td>{{noneIfEmpty($value->total)}}</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{{url('/flats/'.$value->id)}}" class="btn btn-primary">
                                            <i class="fa fa-eye"></i> View </a>
                                        <a href="{{url('/flats/'.$value->id.'/edit')}}" class="btn btn-success">
                                            <i class="fa fa-pencil"></i> Edit </a>
                                        <form class="form-inline" action="{{ url('/flats', ['id' => $value->id]) }}" method="post">
                                            {{ method_field('delete') }} {{ csrf_field() }}
                                            <button class="btn btn-danger" onclick="return confirm('Are you sure you want to Delete?');">
                                                <i class="fa fa-trash"></i> Delete</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/flats/show.blade.php
@extends('layouts.app') @section('content')
<div class="page-title">
    <h3>{{$flats[0]->tower_name}} &amp; Floor - {{$flats[0]->floor_name}}</h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li>
                <a href="{{url('/')}}">Home</a>
            </li>
            <li>
                <a href="{{url('/flats')}}">Flats</a>
            </li>
            <li class="active">View</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
    <div class="row">
        <div class="col-md-6">
            @include('layouts.flash_message')
            <div class="panel panel-white">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            @foreach($flats as $value)
                            <span class="badge badge-primary">Flat No - {{$value->flat_number}}</span>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection